import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  pokedex: {
    flex: 1,
    backgroundColor: '#C62828',
  },
  topSection: {
    backgroundColor: '#C62828',
    paddingTop: 50,
    paddingBottom: 20,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 15,
  },
  blueLightOuter: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#1976D2',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#0D47A1',
  },
  blueLightInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#42A5F5',
    shadowColor: '#2196F3',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 5,
  },
  smallLights: {
    flexDirection: 'row',
    gap: 10,
  },
  smallLight: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#000',
  },
  mainBody: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  scrollContent: {
    padding: 20,
  },
  screenContainer: {
    backgroundColor: '#2C2C2C',
    borderRadius: 15,
    padding: 15,
    marginBottom: 20,
  },
  screenBezel: {
    backgroundColor: '#1A1A1A',
    borderRadius: 10,
    padding: 10,
  },
  screen: {
    backgroundColor: '#9CCC65',
    borderRadius: 8,
    height: 300,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  emptyScreen: {
    alignItems: 'center',
  },
  screenText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1B5E20',
    fontFamily: 'monospace',
    textAlign: 'center',
  },
  screenSubtext: {
    fontSize: 16,
    color: '#33691E',
    fontFamily: 'monospace',
    marginTop: 10,
  },
  screenImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  indicators: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
  },
  redIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#EF5350',
  },
  controls: {
    marginBottom: 20,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 15,
    marginBottom: 15,
  },
  pokeButton: {
    flex: 1,
    backgroundColor: '#424242',
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 2,
    borderBottomWidth: 4,
    borderColor: '#212121',
  },
  pokeButtonText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  analyzeButton: {
    backgroundColor: '#FDD835',
    paddingVertical: 18,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 2,
    borderBottomWidth: 4,
    borderColor: '#F57F17',
  },
  analyzeButtonText: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  resultBox: {
    backgroundColor: '#2C2C2C',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
  },
  resultLabel: {
    color: '#FDD835',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    marginBottom: 5,
  },
  pokemonName: {
    color: '#FFF',
    fontSize: 28,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    marginBottom: 15,
  },
  resultText: {
    color: '#FFF',
    fontSize: 16,
    fontFamily: 'monospace',
    marginTop: 10,
  },
  errorLabel: {
    color: '#EF5350',
    fontSize: 24,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    marginBottom: 10,
  },
  statsContainer: {
    width: '100%',
    marginTop: 10,
  },
  statLabel: {
    color: '#FDD835',
    fontSize: 10,
    fontFamily: 'monospace',
    marginBottom: 5,
  },
  statBar: {
    height: 8,
    backgroundColor: '#1A1A1A',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 5,
  },
  statFill: {
    height: '100%',
    backgroundColor: '#66BB6A',
  },
  statValue: {
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'monospace',
    textAlign: 'right',
  },

  // Details Page Styles
  detailsImageContainer: {
    backgroundColor: '#FFF',
    borderRadius: 15,
    padding: 20,
    alignItems: 'center',
    marginBottom: 20,
  },
  detailsImage: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
  },
  detailsHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  pokemonNumber: {
    color: '#666',
    fontSize: 16,
    fontFamily: 'monospace',
    marginBottom: 5,
  },
  detailsPokemonName: {
    color: '#2C2C2C',
    fontSize: 32,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    marginBottom: 10,
  },
  confidenceBadge: {
    backgroundColor: '#66BB6A',
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderRadius: 15,
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  typesContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 20,
  },
  typeBadge: {
    backgroundColor: '#424242',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
  },
  typeText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  infoGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
  infoCard: {
    flex: 1,
    backgroundColor: '#2C2C2C',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  infoLabel: {
    color: '#FDD835',
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    marginBottom: 5,
  },
  infoValue: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  statsSection: {
    backgroundColor: '#2C2C2C',
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
  },
  sectionTitle: {
    color: '#FDD835',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    marginBottom: 15,
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  statName: {
    color: '#FFF',
    fontSize: 10,
    fontFamily: 'monospace',
    width: 100,
  },
  statBarContainer: {
    flex: 1,
    height: 6,
    backgroundColor: '#1A1A1A',
    borderRadius: 3,
    marginHorizontal: 10,
    overflow: 'hidden',
  },
  statBarFill: {
    height: '100%',
    backgroundColor: '#66BB6A',
  },
  statValueText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    width: 30,
    textAlign: 'right',
  },
  abilitiesSection: {
    backgroundColor: '#2C2C2C',
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
  },
  abilitiesList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  abilityBadge: {
    backgroundColor: '#424242',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 15,
  },
  abilityText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'monospace',
  },
  backButton: {
    backgroundColor: '#C62828',
    paddingVertical: 18,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 2,
    borderBottomWidth: 4,
    borderColor: '#B71C1C',
    marginBottom: 20,
  },
  backButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
});
